{{ if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    grafana_dashboard: "1"
data:
  dittotwins.json: |
{{ .Files.Get "grafana-templates/dashboards/dittotwins.json" | indent 4 }}
{{- end }}
---
{{ if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  eclipse-ditto.json: |
{{ .Files.Get "grafana-templates/datasources/eclipse-ditto.json" | indent 4 }}
{{- end }}
